#!/bin/sh /etc/rc.common


# OpenWrt init.d script to backup/restore the collectd RRD database, to have it persist across (planned) reboots
# https://github.com/pdsakurai/openwrt-rrdbackup
# Forked from: https://github.com/sqrwf/openwrt-rrdbackup/

# This is free and unencumbered software released into the public domain.
# For more information, please refer to <http://unlicense.org/>


# backup target directory and file
readonly BACKUP_DIR=/root
readonly BACKUP_FILE="$BACKUP_DIR/collectd_rrd_backup.tgz"

# directory containing collectd's RRD files (usually /tmp/rrd)
# root relative, i.e. no slash in front (to mitigate tar "leading '/'" warning)
readonly RRD_DIR=/tmp/rrd

# queue rrdbackup to start before collectd starts (80) and stop after collect stops (10):
readonly START=79
readonly STOP=11

# "backup" command to manually backup database (e.g. from cronjob)
# for completeness, "restore" is also possible although I struggle to come up with a use case
readonly EXTRA_COMMANDS="backup restore"
readonly EXTRA_HELP="        backup          Backup current rrd database"

backup() {
	local TMP_FILE=$(mktemp -u)
	tar -czf "$TMP_FILE" -C / "${RRD_DIR#/}"
	mkdir -p "$BACKUP_DIR"
	mv -f "$TMP_FILE" "$BACKUP_FILE"
}

restore() {
	[ -f "$BACKUP_FILE" ] && tar -xzf "$BACKUP_FILE" -C /
}

start() {
	restore
}

stop() {
	backup
}
